[project]
name = "raytracer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.ruff.lint]
extend-select = ["B"]


[dependency-groups]
dev = [
    "ruff>=0.12.3",
]
